name: Native CI workflow

on:
  pull_request:
  push:
    branches:
      - master

jobs:

  build-melodic:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest] #[ubuntu-latest, self-hosted]
      fail-fast: false

    container:
      image: autoware/autoware:bleedingedge-melodic-base
      env:
        ROS_DISTRO: melodic
      options: --user 1001

    steps:

    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Prepare repo
      run: |
        mkdir -p src_tmp/ && mv `find -maxdepth 1 -not -name . -not -name src_tmp` src_tmp/ && mv src_tmp/ src/
        rosdep update
        rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO

    - name: Build and test repo
      run: |
        bash -c 'source /opt/ros/$ROS_DISTRO/setup.bash; \
        colcon build --cmake-args -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fprofile-arcs -ftest-coverage" -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -fprofile-arcs -ftest-coverage" -DCMAKE_BUILD_TYPE=Debug; \
        colcon build --cmake-target tests --cmake-args -DCMAKE_CXX_FLAGS="${CMAKE_CXX_FLAGS} -fprofile-arcs -ftest-coverage" -DCMAKE_C_FLAGS="${CMAKE_C_FLAGS} -fprofile-arcs -ftest-coverage" -DCMAKE_BUILD_TYPE=Debug; \
        colcon test; \
        colcon test-result --verbose'
